#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:
#+ Install nginx
#+ Nginx should be listening on port 80
#+ When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World

if [ ! -x /usr/sbin/nginx ]; then
    sudo apt -y update
    sudo apt install -y --allow-downgrades nginx
    sudo ufw allow 'Nginx HTTP'
fi
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
