#!/usr/bin/env bash
# Configuring HAProxy

sudo apt-get update
sudo apt-get install -y haproxy
proxy_line="
frontend first_frontend
    bind *:80
    mode: http
    default_backend web_servers
    
backend web_servers
    mode: http
    balance roundrobin
    server 4748-web-01 54.175.45.148
    server 4748-web-02 52.207.249.170"

sudo echo "$proxy_line" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
