#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#   receiving a SIGQUIT or SIGTERM.

sudo touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
echo $BASHPID >> /var/run/holbertonscript.pid
while true; do
      echo "To infinity and beyond"
      sleep 2
      trap "echo 'I hate the kill command'; sudo rm /var/run/holbertonscript.pid; exit 1" SIGTERM
      trap "echo 'Y U no love me?!'" SIGINT
      trap "sudo rm /var/run/holbertonscript.pid; exit 1" SIGQUIT
done
